num_runs: 2
num_cores: 4
num_threads: 6
# verbose: 0
verbose: 1
buffer_capacity: 2000
max_request_queue_length: 1600
policy: roundRobin
# policy: fcfs
quantum_size: 5
num_users: 1600
# Stopping criterion is the number of requests to generate (need not finish)
stopping_criterion: 25000 
context_switch_overhead:  0.02


# think_time_distribution:
#   name: c+exp
#   params:
#     c: 20.0
#     lambd: 0.5

# think_time_distribution:
#   name: uniform
#   params:
#     a: 1.0
#     b: 2.0

think_time_distribution:
  name: deterministic
  params:
    c: 6000.0

# service_time_distribution:
#   name: exponential
#   params:
#     lambd: 0.05


# service_time_distribution:
#   name: uniform
#   params:
#     a: 2.0
#     b: 3.0

service_time_distribution:
  name: deterministic
  params:
    c: 10.0

# timeout_distribution:
#   name: c+exp
#   params:
#     c: 150.0
#     lambd: 0.02

timeout_distribution:
  name: deterministic
  params:
    c: 200.0